export const ADMIN_TABLE_LABELS: Record<string, string> = {
  users: 'Пользователи',
  roles: 'Роли',
  permissions: 'Права доступа',
  user_roles: 'Роли пользователей',
  role_permissions: 'Права ролей',
  organizations: 'Организации',
  departments: 'Подразделения',
  territories: 'Территории',
  competencies: 'Компетенции',
  user_competencies: 'Компетенции сотрудников',
  support_groups: 'Группы поддержки',
  support_group_members: 'Состав групп поддержки',
  categories: 'Категории',
  ticket_types: 'Типы заявок',
  ticket_kinds: 'Виды заявок',
  ticket_type_competencies: 'Компетенции типов заявок',
  routing_rules: 'Правила маршрутизации',
  routing_rule_versions: 'Версии правил маршрутизации',
  tickets: 'Тикеты',
  ticket_observers: 'Наблюдатели тикетов',
  ticket_assignments: 'Назначения тикетов',
  ticket_comments: 'Комментарии к тикетам',
  ticket_sla_instances: 'SLA тикетов',
  audit_log: 'Журнал аудита',
  nomenclature: 'Номенклатура',
  warehouses: 'Склады',
  warehouse_stock: 'Остатки на складах',
  equipment_items: 'Оборудование',
  equipment_movements: 'Движение оборудования',
  inventory_receipts: 'Поступления ТМЦ',
  system_integrations: 'Обмены с ИС',
};

export type AdminReference = { table: string; label: string };

export const ADMIN_REFERENCE_COLUMNS: Record<string, Record<string, AdminReference>> = {
  user_roles: { user_id: { table: 'users', label: 'display_name' }, role_id: { table: 'roles', label: 'name' }, assigned_by: { table: 'users', label: 'display_name' } },
  role_permissions: { role_id: { table: 'roles', label: 'name' }, permission_id: { table: 'permissions', label: 'code' } },
  departments: { organization_id: { table: 'organizations', label: 'name' }, manager_id: { table: 'users', label: 'display_name' } },
  user_competencies: { user_id: { table: 'users', label: 'display_name' }, competency_id: { table: 'competencies', label: 'name' } },
  support_groups: { manager_id: { table: 'users', label: 'display_name' }, organization_id: { table: 'organizations', label: 'name' }, department_id: { table: 'departments', label: 'name' }, territory_id: { table: 'territories', label: 'name' } },
  support_group_members: { support_group_id: { table: 'support_groups', label: 'name' }, user_id: { table: 'users', label: 'display_name' } },
  categories: { parent_id: { table: 'categories', label: 'name' } },
  ticket_kinds: { ticket_type_id: { table: 'ticket_types', label: 'name' } },
  ticket_type_competencies: { ticket_type_id: { table: 'ticket_types', label: 'name' }, competency_id: { table: 'competencies', label: 'name' } },
  routing_rules: { created_by: { table: 'users', label: 'display_name' } },
  routing_rule_versions: { rule_id: { table: 'routing_rules', label: 'name' }, created_by: { table: 'users', label: 'display_name' } },
  warehouses: { organization_id: { table: 'organizations', label: 'name' } },
  warehouse_stock: { warehouse_id: { table: 'warehouses', label: 'name' }, nomenclature_id: { table: 'nomenclature', label: 'name' } },
  equipment_items: { warehouse_id: { table: 'warehouses', label: 'name' }, organization_id: { table: 'organizations', label: 'name' }, department_id: { table: 'departments', label: 'name' }, assigned_to: { table: 'users', label: 'display_name' } },
  equipment_movements: { equipment_id: { table: 'equipment_items', label: 'inventory_number' }, organization_id: { table: 'organizations', label: 'name' }, department_id: { table: 'departments', label: 'name' }, employee_id: { table: 'users', label: 'display_name' }, issued_by: { table: 'users', label: 'display_name' }, approver_id: { table: 'users', label: 'display_name' } },
  inventory_receipts: { organization_id: { table: 'organizations', label: 'name' }, warehouse_id: { table: 'warehouses', label: 'name' }, employee_id: { table: 'users', label: 'display_name' }, nomenclature_id: { table: 'nomenclature', label: 'name' } },
};

export const ADMIN_FIELD_LABELS: Record<string, Record<string, string>> = {
  users: { id: 'Идентификатор', external_id: 'Внешний идентификатор', email: 'Электронная почта', display_name: 'Отображаемое имя', is_active: 'Активен', created_at: 'Дата создания', updated_at: 'Дата изменения' },
  roles: { id: 'Идентификатор', code: 'Код роли', name: 'Название роли', description: 'Описание', is_system: 'Системная роль', is_active: 'Активна' },
  permissions: { id: 'Идентификатор', code: 'Код права', description: 'Описание права' },
  user_roles: { user_id: 'Пользователь', role_id: 'Роль', assigned_by: 'Назначил', created_at: 'Дата назначения' },
  role_permissions: { role_id: 'Роль', permission_id: 'Право доступа', effect: 'Эффект', scope: 'Область действия' },
  organizations: { id: 'Идентификатор', code: 'Код организации', name: 'Название организации', is_active: 'Активна' },
  departments: { id: 'Идентификатор', organization_id: 'Организация', code: 'Код подразделения', name: 'Название подразделения', manager_id: 'Руководитель', is_active: 'Активно' },
  territories: { id: 'Идентификатор', code: 'Код территории', name: 'Название территории', geometry: 'Геометрия', is_active: 'Активна' },
  competencies: { id: 'Идентификатор', code: 'Код компетенции', name: 'Название компетенции', description: 'Описание компетенции', is_active: 'Активна' },
  user_competencies: { user_id: 'Пользователь', competency_id: 'Компетенция', level: 'Уровень', valid_from: 'Действует с', valid_to: 'Действует по' },
  support_groups: { id: 'Идентификатор', code: 'Код группы', name: 'Название группы', description: 'Описание группы', manager_id: 'Руководитель', organization_id: 'Организация', department_id: 'Подразделение', territory_id: 'Территория', calendar_code: 'Рабочий календарь', work_schedule: 'График работы', assignment_policy: 'Политика назначения', is_active: 'Активна', created_at: 'Дата создания', updated_at: 'Дата изменения' },
  support_group_members: { support_group_id: 'Группа поддержки', user_id: 'Сотрудник', is_primary: 'Основной исполнитель', valid_from: 'Действует с', valid_to: 'Действует по' },
  categories: { id: 'Идентификатор', code: 'Код категории', name: 'Название категории', parent_id: 'Родительская категория', is_active: 'Активна' },
  ticket_types: { id: 'Идентификатор', code: 'Код типа заявки', name: 'Название типа заявки', is_active: 'Активен' },
  ticket_kinds: { id: 'Идентификатор', ticket_type_id: 'Тип заявки', code: 'Код вида заявки', name: 'Название вида заявки', is_active: 'Активен' },
  ticket_type_competencies: { ticket_type_id: 'Тип заявки', competency_id: 'Компетенция', min_level: 'Минимальный уровень', required: 'Обязательна' },
  routing_rules: { id: 'Идентификатор', code: 'Код правила', name: 'Название правила', event_type: 'Событие', priority: 'Приоритет', status: 'Статус', active_from: 'Действует с', active_to: 'Действует по', current_version: 'Текущая версия', created_by: 'Создал', created_at: 'Дата создания', updated_at: 'Дата изменения' },
  routing_rule_versions: { rule_id: 'Правило маршрутизации', version: 'Версия', conditions: 'Условия', actions: 'Действия', change_comment: 'Комментарий изменения', created_by: 'Создал', created_at: 'Дата создания' },
  tickets: { id: 'Идентификатор', number: 'Номер заявки', subject: 'Тема обращения', description: 'Описание', created_by: 'Создатель', organization_id: 'Организация', department_id: 'Подразделение', territory_id: 'Территория', category_id: 'Категория', ticket_type_id: 'Тип заявки', ticket_kind_id: 'Вид заявки', equipment_id: 'Оборудование', project_id: 'Проект', priority: 'Приоритет', status: 'Статус', support_group_id: 'Группа поддержки', assignee_id: 'Исполнитель', sla_policy_id: 'Политика SLA', route_version: 'Версия маршрута', approval_required: 'Требует согласования', visit_required: 'Требует выезда', repair_required: 'Требуется ремонт', created_at: 'Дата создания', updated_at: 'Дата изменения', closed_at: 'Дата закрытия' },
  ticket_observers: { ticket_id: 'Тикет', user_id: 'Наблюдатель', created_at: 'Дата добавления' },
  ticket_assignments: { id: 'Идентификатор', ticket_id: 'Тикет', support_group_id: 'Группа поддержки', assignee_id: 'Исполнитель', assigned_by: 'Назначил', reason: 'Причина назначения', started_at: 'Назначено с', ended_at: 'Назначено по' },
  ticket_comments: { id: 'Идентификатор', ticket_id: 'Тикет', author_id: 'Автор', body: 'Текст комментария', is_internal: 'Внутренний комментарий', created_at: 'Дата создания' },
  ticket_sla_instances: { id: 'Идентификатор', ticket_id: 'Тикет', policy_id: 'Политика SLA', calendar_code: 'Рабочий календарь', target_at: 'Целевой срок', breached_at: 'Нарушено в', paused_at: 'Приостановлено в', completed_at: 'Завершено в', status: 'Статус', policy_version: 'Версия политики' },
  audit_log: { id: 'Идентификатор', occurred_at: 'Дата события', actor_id: 'Инициатор', actor_type: 'Тип инициатора', action: 'Действие', resource_type: 'Тип объекта', resource_id: 'Идентификатор объекта', before_data: 'Данные до изменения', after_data: 'Данные после изменения', reason: 'Причина', correlation_id: 'Идентификатор корреляции', decision_id: 'Идентификатор решения', ip: 'IP-адрес', user_agent: 'Браузер' },
  nomenclature: { id: 'Идентификатор', code: 'Код номенклатуры', name: 'Наименование', category: 'Категория', unit: 'Единица измерения', is_active: 'Активна', created_at: 'Дата создания', updated_at: 'Дата изменения' },
  warehouses: { id: 'Идентификатор', code: 'Код склада', name: 'Наименование склада', organization_id: 'Организация', address: 'Адрес', is_active: 'Активен', created_at: 'Дата создания' },
  warehouse_stock: { id: 'Идентификатор', warehouse_id: 'Склад', nomenclature_id: 'Номенклатура', quantity: 'Количество', comment: 'Комментарий', is_used: 'Б/У', updated_at: 'Дата изменения' },
  equipment_items: { id: 'Идентификатор', inventory_number: 'Инвентарный номер', name: 'Наименование', equipment_type: 'Тип оборудования', serial_number: 'Серийный номер', status: 'Состояние', toner_level: 'Остаток тонера, %', toner_available: 'Тонер в наличии', warehouse_id: 'Склад', organization_id: 'Организация', department_id: 'Подразделение', assigned_to: 'Ответственный', comment: 'Комментарий', is_active: 'Активно', created_at: 'Дата создания', updated_at: 'Дата изменения' },
  equipment_movements: { id: 'Идентификатор', document_number: 'Номер документа', equipment_id: 'Оборудование', organization_id: 'Организация', department_id: 'Подразделение', employee_id: 'Сотрудник', issued_by: 'Выдал', status: 'Статус документа', requires_approval: 'Требует согласования', approver_id: 'Согласующий', comment: 'Комментарий', created_at: 'Дата создания' },
  inventory_receipts: { id: 'Идентификатор', document_number: 'Номер документа', organization_id: 'Организация', warehouse_id: 'Склад', employee_id: 'Получил', nomenclature_id: 'Номенклатура', quantity: 'Количество', comment: 'Комментарий', created_at: 'Дата создания' },
  system_integrations: { id: 'Идентификатор', code: 'Код подключения', name: 'Название системы', integration_type: 'Тип подключения', endpoint: 'Адрес подключения', database_name: 'Имя базы данных', description: 'Описание', api_description: 'Описание API', is_active: 'Активно', last_sync_at: 'Последний обмен', created_at: 'Дата создания' },
};
