import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { basename, extname, join } from 'node:path';
import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { DatabaseService } from './database.service';

export type SecurityContext = { role: string; userId: string };
type Field = { name: string; label: string; type: 'text' | 'textarea' | 'date' | 'datetime' | 'number' | 'boolean' | 'select'; options?: string[]; required?: boolean };

const entityMeta: Record<string, { label: string; description: string; fields: Field[] }> = {
  incident: { label: 'Инциденты', description: 'Регистрация, расследование и контроль инцидентов ИБ.', fields: [
    { name: 'category', label: 'Категория', type: 'select', options: ['Фишинг','Вредоносное ПО','Вирус','Компрометация учётной записи','Несанкционированный доступ','Утечка информации','Утрата оборудования','Подозрительная активность','Нарушение доступности','Сетевой инцидент','Нарушение политики ИБ','Социальная инженерия','Прочее'], required: true },
    { name: 'source', label: 'Источник обнаружения', type: 'text' }, { name: 'detectedAt', label: 'Дата обнаружения', type: 'datetime' }, { name: 'ip', label: 'IP-адрес', type: 'text' }, { name: 'hostname', label: 'Hostname', type: 'text' }, { name: 'personalData', label: 'Есть персональные данные', type: 'boolean' }, { name: 'leakage', label: 'Есть утечка информации', type: 'boolean' }, { name: 'affectedUsers', label: 'Затронуто пользователей', type: 'number' }, { name: 'measures', label: 'Принятые меры', type: 'textarea' }, { name: 'visibilityLevel', label: 'Уровень видимости', type: 'select', options: ['Стандартный','Ограниченный','Конфиденциальный','Только ИБ'] },
  ] },
  violation: { label: 'Нарушения', description: 'Нарушения требований и политик информационной безопасности.', fields: [
    { name: 'violationType', label: 'Тип нарушения', type: 'select', options: ['Передача пароля','Чужая учётная запись','ПО без согласования','Запрещённое ПО','Стороннее оборудование','Передача информации третьему лицу','Нарушение требований к носителям','Нарушение удалённого доступа','Нарушение политики паролей','Рабочее место без блокировки','Нарушение правил работы с ПДн'], required: true }, { name: 'employee', label: 'Сотрудник', type: 'text' }, { name: 'rule', label: 'Нарушенное правило', type: 'text' }, { name: 'incident', label: 'Связанный инцидент', type: 'text' }, { name: 'explanation', label: 'Объяснение сотрудника', type: 'textarea' }, { name: 'decision', label: 'Принятое решение', type: 'textarea' },
  ] },
  access: { label: 'Доступы', description: 'Заявки на предоставление и изменение доступа.', fields: [
    { name: 'employee', label: 'Сотрудник', type: 'text', required: true }, { name: 'system', label: 'Информационная система', type: 'text', required: true }, { name: 'resource', label: 'Ресурс', type: 'text' }, { name: 'requestedRole', label: 'Требуемая роль', type: 'text' }, { name: 'currentRights', label: 'Текущие права', type: 'textarea' }, { name: 'requiredRights', label: 'Требуемые права', type: 'textarea' }, { name: 'startDate', label: 'Дата начала', type: 'date' }, { name: 'endDate', label: 'Дата окончания', type: 'date' }, { name: 'temporary', label: 'Временный доступ', type: 'boolean' }, { name: 'securityApprovalRequired', label: 'Требуется согласование ИБ', type: 'boolean' },
  ] },
  privileged: { label: 'Привилегированные доступы', description: 'Контроль учетных записей с расширенными правами.', fields: [
    { name: 'employee', label: 'Сотрудник', type: 'text' }, { name: 'system', label: 'Система', type: 'text', required: true }, { name: 'account', label: 'Учётная запись', type: 'text', required: true }, { name: 'accessType', label: 'Тип доступа', type: 'select', options: ['Domain Admin','Local Administrator','root','sudo','Администратор БД','Администратор 1С','Администратор приложения','VPN Admin','Сетевое оборудование','Другое'] }, { name: 'rights', label: 'Права', type: 'textarea' }, { name: 'grantDate', label: 'Дата предоставления', type: 'date' }, { name: 'endDate', label: 'Дата окончания', type: 'date' }, { name: 'reviewDate', label: 'Следующий пересмотр', type: 'date' },
  ] },
  vulnerability: { label: 'Уязвимости', description: 'Реестр уязвимостей и контроль сроков устранения.', fields: [
    { name: 'cve', label: 'CVE', type: 'text' }, { name: 'cvss', label: 'CVSS', type: 'number' }, { name: 'system', label: 'Информационная система', type: 'text' }, { name: 'server', label: 'Сервер', type: 'text' }, { name: 'ip', label: 'IP-адрес', type: 'text' }, { name: 'software', label: 'ПО', type: 'text' }, { name: 'version', label: 'Версия', type: 'text' }, { name: 'dueDate', label: 'Плановая дата устранения', type: 'date' }, { name: 'remediation', label: 'Способ устранения', type: 'textarea' }, { name: 'compensatingMeasures', label: 'Компенсирующие меры', type: 'textarea' },
  ] },
  information_system: { label: 'Информационные системы', description: 'Реестр систем, владельцев, интеграций и признаков защиты.', fields: [
    { name: 'code', label: 'Код', type: 'text', required: true }, { name: 'owner', label: 'Владелец', type: 'text' }, { name: 'technicalResponsible', label: 'Технический ответственный', type: 'text' }, { name: 'type', label: 'Тип системы', type: 'text' }, { name: 'address', label: 'Адрес', type: 'text' }, { name: 'url', label: 'URL', type: 'text' }, { name: 'category', label: 'Категория информации', type: 'text' }, { name: 'personalData', label: 'Есть ПДн', type: 'boolean' }, { name: 'commercialSecret', label: 'Коммерческая тайна', type: 'boolean' }, { name: 'internetAccess', label: 'Доступ из интернета', type: 'boolean' }, { name: 'remoteAccess', label: 'Удалённый доступ', type: 'boolean' }, { name: 'rpo', label: 'RPO', type: 'text' }, { name: 'rto', label: 'RTO', type: 'text' },
  ] },
  pdsn: { label: 'ИСПДн', description: 'Реестр информационных систем персональных данных.', fields: [
    { name: 'system', label: 'Связанная система', type: 'text' }, { name: 'operator', label: 'Оператор', type: 'text' }, { name: 'owner', label: 'Владелец', type: 'text' }, { name: 'purpose', label: 'Цели обработки', type: 'textarea' }, { name: 'subjectCategories', label: 'Категории субъектов', type: 'text' }, { name: 'personalDataCategories', label: 'Категории ПДн', type: 'text' }, { name: 'securityLevel', label: 'Уровень защищённости', type: 'select', options: ['УЗ-1','УЗ-2','УЗ-3','УЗ-4','Не определён'] }, { name: 'internetAccess', label: 'Интернет-доступ', type: 'boolean' }, { name: 'lastAuditDate', label: 'Дата последней проверки', type: 'date' },
  ] },
  software: { label: 'Программное обеспечение', description: 'Реестр установленного и разрешённого программного обеспечения.', fields: [
    { name: 'developer', label: 'Разработчик', type: 'text' }, { name: 'version', label: 'Версия', type: 'text' }, { name: 'category', label: 'Категория', type: 'text' }, { name: 'license', label: 'Лицензия', type: 'text' }, { name: 'allowed', label: 'Разрешено', type: 'boolean' }, { name: 'prohibited', label: 'Запрещено', type: 'boolean' }, { name: 'requiresApproval', label: 'Требует согласования', type: 'boolean' }, { name: 'officialUrl', label: 'Официальный сайт', type: 'text' },
  ] },
  media: { label: 'Носители информации', description: 'Учет съёмных носителей, выдачи, возврата и шифрования.', fields: [
    { name: 'inventoryNumber', label: 'Инвентарный номер', type: 'text' }, { name: 'serialNumber', label: 'Серийный номер', type: 'text' }, { name: 'mediaType', label: 'Тип носителя', type: 'select', options: ['USB Flash','Внешний HDD/SSD','Карта памяти','Токен','Оптический диск','Другое'] }, { name: 'employee', label: 'Сотрудник', type: 'text' }, { name: 'manufacturer', label: 'Производитель', type: 'text' }, { name: 'capacity', label: 'Объём', type: 'text' }, { name: 'encrypted', label: 'Есть шифрование', type: 'boolean' }, { name: 'returnDate', label: 'Дата возврата', type: 'date' },
  ] },
  audit: { label: 'Проверки', description: 'Плановые и внеплановые проверки информационной безопасности.', fields: [
    { name: 'auditType', label: 'Тип проверки', type: 'select', options: ['Плановая','Внеплановая','Внутренняя','Внешняя','Аудит доступа','Аудит ИСПДн','Проверка подразделения','Проверка информационной системы','Аудит документации'] }, { name: 'object', label: 'Объект проверки', type: 'text' }, { name: 'startDate', label: 'Дата начала', type: 'date' }, { name: 'endDate', label: 'Дата окончания', type: 'date' }, { name: 'auditor', label: 'Проверяющий', type: 'text' }, { name: 'program', label: 'Программа проверки', type: 'textarea' }, { name: 'results', label: 'Результаты', type: 'textarea' },
  ] },
  risk: { label: 'Риски', description: 'Оценка и обработка рисков ИБ по матрице 5×5.', fields: [
    { name: 'asset', label: 'Актив', type: 'text' }, { name: 'threat', label: 'Угроза', type: 'text' }, { name: 'probability', label: 'Вероятность (1–5)', type: 'number', required: true }, { name: 'impact', label: 'Влияние (1–5)', type: 'number', required: true }, { name: 'strategy', label: 'Стратегия обработки', type: 'select', options: ['снизить','избежать','передать','принять'] }, { name: 'existingMeasures', label: 'Существующие меры', type: 'textarea' }, { name: 'residualRisk', label: 'Остаточный риск', type: 'number' }, { name: 'reviewDate', label: 'Дата пересмотра', type: 'date' },
  ] },
  action: { label: 'Мероприятия', description: 'Задачи по устранению замечаний, рисков и уязвимостей.', fields: [
    { name: 'source', label: 'Источник', type: 'text' }, { name: 'assignee', label: 'Исполнитель', type: 'text', required: true }, { name: 'controller', label: 'Контролёр', type: 'text' }, { name: 'dueDate', label: 'Срок', type: 'date', required: true }, { name: 'priority', label: 'Приоритет', type: 'select', options: ['Низкий','Средний','Высокий','Критический'] }, { name: 'result', label: 'Результат', type: 'textarea' },
  ] },
  document: { label: 'Документы ИБ', description: 'Локальные документы ИБ с контролем версий и актуальности.', fields: [
    { name: 'documentType', label: 'Тип документа', type: 'select', options: ['Политика информационной безопасности','Политика обработки ПДн','Положение об управлении доступом','Парольная политика','Регламент реагирования на инциденты','Модель угроз','Акт определения уровня защищённости','Инструкция','Акт','Другое'], required: true }, { name: 'version', label: 'Версия', type: 'text' }, { name: 'approvedDate', label: 'Дата утверждения', type: 'date' }, { name: 'effectiveDate', label: 'Дата вступления в силу', type: 'date' }, { name: 'reviewDate', label: 'Следующий пересмотр', type: 'date' }, { name: 'reviewPeriod', label: 'Периодичность, мес.', type: 'number' }, { name: 'confidentiality', label: 'Конфиденциальность', type: 'select', options: ['Стандартный','Ограниченный','Конфиденциальный'] },
  ] },
  regulation: { label: 'Нормативные требования', description: 'Редактируемый реестр НПА и требований контроля.', fields: [
    { name: 'lawNumber', label: 'Номер НПА', type: 'text', required: true }, { name: 'article', label: 'Статья / пункт', type: 'text' }, { name: 'category', label: 'Категория', type: 'select', options: ['Персональные данные','Информационная безопасность','КИИ','Коммерческая тайна','Криптографическая защита','Хранение информации','Другое'] }, { name: 'effectiveFrom', label: 'Дата начала действия', type: 'date' }, { name: 'source', label: 'Источник', type: 'text' }, { name: 'sourceUrl', label: 'Ссылка', type: 'text' },
  ] },
  exception: { label: 'Реестр исключений', description: 'Временные исключения из требований с контролем срока.', fields: [
    { name: 'object', label: 'Объект', type: 'text' }, { name: 'requirement', label: 'Требование', type: 'text' }, { name: 'reason', label: 'Причина', type: 'textarea', required: true }, { name: 'compensatingMeasures', label: 'Компенсирующие меры', type: 'textarea' }, { name: 'startDate', label: 'Дата начала', type: 'date' }, { name: 'endDate', label: 'Дата окончания', type: 'date', required: true }, { name: 'approver', label: 'Согласующий ИБ', type: 'text' },
  ] },
  event: { label: 'События ИБ', description: 'События от EDR, SIEM, DLP и других источников.', fields: [
    { name: 'source', label: 'Источник', type: 'text', required: true }, { name: 'externalId', label: 'Внешний идентификатор', type: 'text' }, { name: 'category', label: 'Категория', type: 'text' }, { name: 'sourceIp', label: 'IP источника', type: 'text' }, { name: 'destinationIp', label: 'IP назначения', type: 'text' }, { name: 'hostname', label: 'Hostname', type: 'text' }, { name: 'username', label: 'Пользователь', type: 'text' }, { name: 'rawData', label: 'Исходные данные', type: 'textarea' },
  ] },
  kii: { label: 'Объекты КИИ', description: 'Опциональный реестр объектов критической информационной инфраструктуры.', fields: [
    { name: 'subject', label: 'Субъект КИИ', type: 'text' }, { name: 'objectType', label: 'Тип объекта', type: 'text' }, { name: 'category', label: 'Категория', type: 'text' }, { name: 'categorizationDate', label: 'Дата категорирования', type: 'date' }, { name: 'responsible', label: 'Ответственный', type: 'text' }, { name: 'decision', label: 'Решение', type: 'textarea' },
  ] },
  setting: { label: 'Настройки ИБ', description: 'Настройки SLA, уведомлений и порогов матрицы рисков.', fields: [
    { name: 'key', label: 'Ключ настройки', type: 'text', required: true }, { name: 'value', label: 'Значение', type: 'text', required: true }, { name: 'comment', label: 'Комментарий', type: 'textarea' },
  ] },
};

const statuses: Record<string, string[]> = {
  incident: ['new','accepted','investigation','localization','remediation','control','closed','false_positive','duplicate','cancelled'], violation: ['new','in_review','confirmed','action_required','closed'], access: ['new','approval','approved','execution','confirmation','closed','rejected'], privileged: ['active','review','expired','revoked'], vulnerability: ['detected','confirmed','assigned','remediating','fixed','verification','closed','risk_accepted','false_positive'], information_system: ['draft','active','archived'], pdsn: ['draft','active','review','archived'], software: ['on_review','allowed','prohibited','restricted'], media: ['warehouse','issued','blocked','lost','destroyed','written_off'], audit: ['planned','in_progress','control','closed'], risk: ['open','processing','accepted','closed'], action: ['new','assigned','in_progress','awaiting_check','completed','rejected','overdue'], document: ['draft','approval','rework','approval_manager','active','review_required','archived','cancelled'], regulation: ['draft','active','expired'], exception: ['draft','approval','active','expired','cancelled'], event: ['new','analysis','incident','false_positive','closed'], kii: ['draft','active','archived'], setting: ['active','disabled'],
};

const statusLabels: Record<string, string> = { new: 'Новое', accepted: 'Принят в работу', investigation: 'Расследование', localization: 'Локализация', remediation: 'Устранение', control: 'Контроль', closed: 'Закрыт', false_positive: 'Ложное срабатывание', duplicate: 'Дубликат', cancelled: 'Отменён', in_review: 'На рассмотрении', confirmed: 'Подтверждено', action_required: 'Требует мероприятий', approval: 'На согласовании', approved: 'Согласовано', execution: 'Исполнение', confirmation: 'Подтверждение', rejected: 'Отклонено', active: 'Действует', review: 'На пересмотре', expired: 'Истёк срок', revoked: 'Отозван', detected: 'Обнаружена', assigned: 'Назначена', remediating: 'Исправляется', fixed: 'Исправлена', verification: 'Проверка', risk_accepted: 'Риск принят', draft: 'Черновик', archived: 'Архив', on_review: 'На проверке', allowed: 'Разрешено', prohibited: 'Запрещено', restricted: 'Ограничено', warehouse: 'На складе', issued: 'Выдан', blocked: 'Заблокирован', lost: 'Потерян', destroyed: 'Уничтожен', written_off: 'Списан', planned: 'Плановая', in_progress: 'В работе', processing: 'Обработка', awaiting_check: 'Ожидает проверки', completed: 'Выполнено', overdue: 'Просрочено', rework: 'На доработке', approval_manager: 'На утверждении', review_required: 'Требует пересмотра', disabled: 'Отключена', analysis: 'Анализ', incident: 'Инцидент' };
const severities = ['low','medium','high','critical'];
const severityLabels: Record<string, string> = { low: 'Низкая', medium: 'Средняя', high: 'Высокая', critical: 'Критическая' };
const entityLabels = Object.fromEntries(Object.entries(entityMeta).map(([key, value]) => [key, value.label]));

@Injectable()
export class SecurityService {
  private readonly uploadRoot = join(process.cwd(), process.env.SECURITY_UPLOAD_DIR ?? 'storage/security');
  constructor(private readonly database: DatabaseService) {}

  meta() { return { entities: Object.entries(entityMeta).map(([type, value]) => ({ type, ...value, statuses: (statuses[type] ?? []).map((code) => ({ code, label: statusLabels[code] ?? code })) })), severity: severities.map((code) => ({ code, label: severityLabels[code] })) }; }

  private assertRead(context: SecurityContext) { if (!['admin','security_specialist','security_manager','department_manager','security_executor','user','initiator'].includes(context.role)) throw new ForbiddenException('Нет доступа к модулю информационной безопасности'); }
  private assertWrite(context: SecurityContext) { this.assertRead(context); if (!['admin','security_specialist','security_manager'].includes(context.role)) throw new ForbiddenException('Недостаточно прав для изменения объекта ИБ'); }
  private assertEntity(type: string): asserts type is keyof typeof entityMeta { if (!entityMeta[type]) throw new BadRequestException('Неизвестный раздел ИБ'); }

  async list(type: string | undefined, query: Record<string, string | undefined>, context: SecurityContext) {
    this.assertRead(context); if (type) this.assertEntity(type);
    const page = Math.max(1, Number(query.page ?? 1)); const pageSize = Math.min(100, Math.max(1, Number(query.pageSize ?? 20))); const values: unknown[] = []; const where: string[] = ['deleted_at IS NULL'];
    if (type) { values.push(type); where.push(`entity_type = $${values.length}`); }
    if (query.status) { values.push(query.status); where.push(`status = $${values.length}`); }
    if (query.severity) { values.push(query.severity); where.push(`severity = $${values.length}`); }
    if (query.search) { values.push(`%${query.search}%`); where.push(`(title ILIKE $${values.length} OR description ILIKE $${values.length} OR fields::text ILIKE $${values.length})`); }
    const predicate = where.join(' AND '); const count = await this.database.query<{ count: string }>(`SELECT count(*)::text AS count FROM security_records WHERE ${predicate}`, values); values.push(pageSize, (page - 1) * pageSize);
    const result = await this.database.query(`SELECT s.*, u.display_name AS owner_name, a.display_name AS assignee_name FROM security_records s LEFT JOIN users u ON u.id=s.owner_id LEFT JOIN users a ON a.id=s.assignee_id WHERE ${predicate.replaceAll('entity_type', 's.entity_type').replaceAll('status', 's.status').replaceAll('severity', 's.severity').replaceAll('deleted_at', 's.deleted_at').replaceAll('title', 's.title').replaceAll('description', 's.description').replaceAll('fields::text', 's.fields::text')} ORDER BY s.updated_at DESC LIMIT $${values.length - 1} OFFSET $${values.length}`, values);
    return { records: result.rows.map((row) => this.present(row)), total: Number(count.rows[0]?.count ?? 0), page, pageSize };
  }

  async get(id: string, context: SecurityContext) {
    this.assertRead(context); const result = await this.database.query(`SELECT s.*, u.display_name AS owner_name, a.display_name AS assignee_name FROM security_records s LEFT JOIN users u ON u.id=s.owner_id LEFT JOIN users a ON a.id=s.assignee_id WHERE s.id=$1 AND s.deleted_at IS NULL`, [id]); if (!result.rows[0]) throw new NotFoundException('Объект ИБ не найден');
    const comments = await this.database.query(`SELECT c.*, u.display_name AS author_name FROM security_record_comments c JOIN users u ON u.id=c.author_id WHERE c.record_id=$1 ORDER BY c.created_at`, [id]);
    const attachments = await this.database.query(`SELECT id, original_file_name, mime_type, file_size, uploaded_by, created_at FROM security_record_attachments WHERE record_id=$1 ORDER BY created_at`, [id]);
    const history = await this.database.query(`SELECT occurred_at, action, actor_id, before_data, after_data FROM audit_log WHERE resource_type='security_record' AND resource_id=$1 ORDER BY occurred_at DESC`, [id]);
    return { record: { ...this.present(result.rows[0]), comments: comments.rows, attachments: attachments.rows, history: history.rows } };
  }

  async create(input: Record<string, unknown>, context: SecurityContext) {
    this.assertWrite(context); const type = String(input.entityType ?? input.type ?? ''); this.assertEntity(type); const title = String(input.title ?? '').trim(); if (!title) throw new BadRequestException('Название обязательно'); const fields = this.cleanFields(input.fields);
    const status = String(input.status ?? statuses[type][0] ?? 'new'); const severity = input.severity ? String(input.severity) : null; const createdBy = await this.resolveUser(context.userId);
    const result = await this.database.query(`INSERT INTO security_records (entity_type,title,description,status,severity,visibility_level,organization_id,department_id,owner_id,assignee_id,source_ticket_id,due_date,review_date,fields,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *`, [type,title,input.description ? String(input.description) : null,status,severity,String(input.visibilityLevel ?? 'standard'),this.uuidOrNull(input.organizationId),this.uuidOrNull(input.departmentId),this.uuidOrNull(input.ownerId),this.uuidOrNull(input.assigneeId),this.uuidOrNull(input.sourceTicketId),this.dateOrNull(input.dueDate),this.dateOrNull(input.reviewDate),JSON.stringify(fields),createdBy]);
    await this.audit(context, 'create', String(result.rows[0].id), null, result.rows[0]); return this.get(String(result.rows[0].id), context);
  }

  async update(id: string, input: Record<string, unknown>, context: SecurityContext) {
    this.assertWrite(context); const current = await this.get(id, context); const values: unknown[] = []; const set: string[] = [];
    for (const [column, value] of [['title', input.title],['description', input.description],['status', input.status],['severity', input.severity],['visibility_level', input.visibilityLevel],['organization_id', input.organizationId],['department_id', input.departmentId],['owner_id', input.ownerId],['assignee_id', input.assigneeId],['source_ticket_id', input.sourceTicketId],['due_date', input.dueDate],['review_date', input.reviewDate]] as const) if (value !== undefined) { values.push(column.endsWith('_id') ? this.uuidOrNull(value) : column.endsWith('_date') ? this.dateOrNull(value) : value === null ? null : String(value)); set.push(`${column}=$${values.length}`); }
    if (input.fields !== undefined) { values.push(JSON.stringify({ ...(current.record.fields ?? {}), ...this.cleanFields(input.fields) })); set.push(`fields=$${values.length}::jsonb`); }
    if (!set.length) throw new BadRequestException('Нет изменяемых полей'); set.push('updated_at=now()'); values.push(id); const result = await this.database.query(`UPDATE security_records SET ${set.join(', ')} WHERE id=$${values.length} AND deleted_at IS NULL RETURNING *`, values); if (!result.rows[0]) throw new NotFoundException('Объект ИБ не найден'); await this.audit(context, 'update', id, current.record, result.rows[0]); return this.get(id, context);
  }

  async remove(id: string, context: SecurityContext) { this.assertWrite(context); const current = await this.get(id, context); await this.database.query('UPDATE security_records SET deleted_at=now(), updated_at=now() WHERE id=$1', [id]); await this.audit(context, 'delete', id, current.record, { deleted: true }); return { deleted: true }; }
  async comment(id: string, body: Record<string, unknown>, context: SecurityContext) { this.assertRead(context); const text = String(body.body ?? '').trim(); if (!text) throw new BadRequestException('Комментарий не может быть пустым'); await this.get(id, context); const author = await this.resolveUser(context.userId); const result = await this.database.query('INSERT INTO security_record_comments (record_id,author_id,body) VALUES ($1,$2,$3) RETURNING *', [id,author,text]); await this.audit(context, 'comment', id, null, { body: text }); return result.rows[0]; }

  async addAttachment(id: string, input: Record<string, unknown>, context: SecurityContext) { this.assertWrite(context); await this.get(id, context); const original = basename(String(input.fileName ?? '').trim()); const mime = String(input.mimeType ?? '').toLowerCase(); const allowed = new Set(['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','image/jpeg','image/png','text/plain','application/zip']); const extension = extname(original).toLowerCase(); if (!original || !allowed.has(mime) || !['.pdf','.doc','.docx','.xls','.xlsx','.jpg','.jpeg','.png','.txt','.zip'].includes(extension)) throw new BadRequestException('Недопустимый тип файла'); const raw = String(input.fileData ?? ''); const encoded = raw.includes(',') ? raw.slice(raw.indexOf(',') + 1) : raw; const data = Buffer.from(encoded, 'base64'); const max = Number(process.env.MAX_SECURITY_FILE_SIZE_MB ?? 50) * 1024 * 1024; if (!data.length || data.length > max) throw new BadRequestException(`Размер файла не должен превышать ${process.env.MAX_SECURITY_FILE_SIZE_MB ?? 50} МБ`); await mkdir(this.uploadRoot, { recursive: true }); const stored = `${randomUUID()}${extension}`; const path = join(this.uploadRoot, stored); await writeFile(path, data); const user = await this.resolveUser(context.userId); const result = await this.database.query('INSERT INTO security_record_attachments (record_id,file_name,original_file_name,file_path,mime_type,file_size,uploaded_by) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id,original_file_name,mime_type,file_size,created_at', [id,stored,original,path,mime,data.length,user]); await this.audit(context, 'attachment_add', id, null, result.rows[0]); return { attachment: result.rows[0] }; }
  async download(id: string, attachmentId: string, context: SecurityContext) { this.assertRead(context); const result = await this.database.query('SELECT * FROM security_record_attachments WHERE id=$1 AND record_id=$2', [attachmentId,id]); if (!result.rows[0]) throw new NotFoundException('Файл не найден'); await this.get(id, context); return { attachment: result.rows[0], data: await readFile(result.rows[0].file_path) }; }

  async dashboard(context: SecurityContext) { this.assertRead(context); const count = async (where: string, values: unknown[] = []) => Number((await this.database.query<{ count: string }>(`SELECT count(*)::text AS count FROM security_records WHERE deleted_at IS NULL AND ${where}`, values)).rows[0]?.count ?? 0); const [openIncidents, criticalIncidents, openVulnerabilities, criticalVulnerabilities, approvalAccess, overdueActions, reviewDocuments, openRisks, monthViolations, activeExceptions] = await Promise.all([count("entity_type='incident' AND status NOT IN ('closed','cancelled','false_positive','duplicate')"), count("entity_type='incident' AND severity='critical' AND status NOT IN ('closed','cancelled')"), count("entity_type='vulnerability' AND status NOT IN ('closed','fixed','false_positive')"), count("entity_type='vulnerability' AND severity='critical' AND status NOT IN ('closed','fixed')"), count("entity_type='access' AND status='approval'"), count("entity_type='action' AND due_date < current_date AND status NOT IN ('completed','closed')"), count("entity_type='document' AND status='review_required'"), count("entity_type='risk' AND status IN ('open','processing')"), count("entity_type='violation' AND created_at >= date_trunc('month', now())"), count("entity_type='exception' AND status='active' AND due_date >= current_date")]); const bySeverity = await this.database.query(`SELECT coalesce(severity,'не задана') AS label, count(*)::int AS value FROM security_records WHERE deleted_at IS NULL AND entity_type IN ('incident','vulnerability') GROUP BY severity ORDER BY value DESC`); const byType = await this.database.query(`SELECT entity_type AS label, count(*)::int AS value FROM security_records WHERE deleted_at IS NULL GROUP BY entity_type ORDER BY value DESC`); return { cards: [{ key:'openIncidents',label:'Открытые инциденты',value:openIncidents,type:'incident' },{ key:'criticalIncidents',label:'Критические инциденты',value:criticalIncidents,type:'incident',severity:'critical' },{ key:'overdueActions',label:'Просроченные мероприятия',value:overdueActions,type:'action',status:'overdue' },{ key:'openVulnerabilities',label:'Открытые уязвимости',value:openVulnerabilities,type:'vulnerability' },{ key:'criticalVulnerabilities',label:'Критические уязвимости',value:criticalVulnerabilities,type:'vulnerability',severity:'critical' },{ key:'approvalAccess',label:'Доступы на согласовании',value:approvalAccess,type:'access',status:'approval' },{ key:'reviewDocuments',label:'Документы на актуализации',value:reviewDocuments,type:'document',status:'review_required' },{ key:'openRisks',label:'Открытые риски',value:openRisks,type:'risk' },{ key:'monthViolations',label:'Нарушения за месяц',value:monthViolations,type:'violation' },{ key:'activeExceptions',label:'Активные исключения',value:activeExceptions,type:'exception',status:'active' }], charts: { bySeverity: bySeverity.rows, byType: byType.rows } }; }

  async webhook(input: Record<string, unknown>, context: SecurityContext) { this.assertWrite(context); return this.create({ type:'event', title: String(input.description ?? input.externalId ?? 'Внешнее событие ИБ'), description: String(input.description ?? ''), severity: input.severity, fields: input }, context); }
  private present(row: any) { return { ...row, type: row.entity_type, entity_label: entityLabels[row.entity_type] ?? row.entity_type, status_label: statusLabels[row.status] ?? row.status, severity_label: severityLabels[row.severity] ?? row.severity, fields: row.fields ?? {} }; }
  private cleanFields(value: unknown) { return value && typeof value === 'object' && !Array.isArray(value) ? value : {}; }
  private uuidOrNull(value: unknown) { const text = value === undefined || value === null || value === '' ? null : String(value); return text && /^[0-9a-f-]{36}$/i.test(text) ? text : null; }
  private dateOrNull(value: unknown) { return value === undefined || value === null || value === '' ? null : String(value); }
  private async resolveUser(userId: string) { if (/^[0-9a-f-]{36}$/i.test(userId)) { const found = await this.database.query('SELECT id FROM users WHERE id=$1', [userId]); if (found.rows[0]) return userId; } const first = await this.database.query<{ id: string }>('SELECT id FROM users ORDER BY created_at LIMIT 1'); if (!first.rows[0]) throw new BadRequestException('В базе нет пользователя для записи аудита'); return first.rows[0].id; }
  private async audit(context: SecurityContext, action: string, id: string, beforeData: unknown, afterData: unknown) { const actor = await this.resolveUser(context.userId); await this.database.query('INSERT INTO audit_log (actor_id,action,resource_type,resource_id,before_data,after_data,reason) VALUES ($1,$2,$3,$4,$5,$6,$7)', [actor,action,'security_record',id,beforeData ? JSON.stringify(beforeData) : null,afterData ? JSON.stringify(afterData) : null,`Роль: ${context.role}`]); }
}

export { entityMeta, statusLabels, severityLabels };
